# Generated by Django 3.2.16 on 2022-12-27 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodmenu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='image',
            field=models.CharField(default='https://png.pngtree.com/png-clipart/20190612/original/pngtree-black-and-white-variety-of-food-png-image_3319164.jpg', max_length=512),
        ),
    ]
